---
config:
  layout: elk
---
flowchart LR
  RouteOracle[Route Oracle]
  Redis[(Redis)]
  Postgres[(Postgres)]
  FleetHandler[Fleet Handler <br> ]
  RobotConnector[Robot Connector]
  OrderStore[Order Store]
  WarehouseController[Warehouse <br> Controller]
  User[User]
  GraphQL[GraphQL <br> Interface]

  GraphQL <--> User

  GraphQL --> WarehouseController
  OrderStore --> GraphQL
  FleetHandler --> GraphQL

  OrderStore <--> Redis

  WarehouseController <--> OrderStore

  WarehouseController --> FleetHandler

  Postgres <--> RouteOracle
  RouteOracle --> RobotConnector
  FleetHandler --> RobotConnector
  RobotConnector --> Robot
